# Generated by Django 3.0.6 on 2020-05-28 15:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.TextField()),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True)),
                ('dateTimeModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phoneNumber', models.CharField(max_length=16, unique=True)),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True)),
                ('dateTimeModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phoneNumber', models.CharField(max_length=16, unique=True)),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True)),
                ('dateTimeModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('itemsOrdered', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('amountDue', models.FloatField()),
                ('amountPaid', models.FloatField(default=0)),
                ('amountOutstanding', models.FloatField()),
                ('dateAndTimeOfOrder', models.DateTimeField(auto_now_add=True)),
                ('preOrderDateTime', models.DateTimeField(null=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_vendor_app.Customer')),
                ('orderStatusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_vendor_app.OrderStatus')),
                ('vendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_vendor_app.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True)),
                ('messageStatusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_vendor_app.MessageStatus')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_vendor_app.Order')),
                ('subjectUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_vendor_app.Auth')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=16)),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True)),
                ('isRecurring', models.BooleanField(default=False)),
                ('frequencyOfReoccurrence', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=7)),
                ('vendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_vendor_app.Vendor')),
            ],
        ),
    ]
