# Generated by Django 3.0.6 on 2020-05-17 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='fromVendor',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='toCustomer',
        ),
        migrations.AddField(
            model_name='notification',
            name='subjectUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='food_vendor_app.Auth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auth',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
