# Generated by Django 3.0.6 on 2020-05-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0002_auto_20200517_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='auth_id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='auth_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
