# Generated by Django 3.0.6 on 2020-05-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0003_auto_20200517_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.TextField(),
        ),
    ]
