# Generated by Django 3.0.6 on 2020-05-18 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0004_auto_20200518_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=16)),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True)),
                ('dateTimeModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='auth',
            name='userTypeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food_vendor_app.UserType'),
            preserve_default=False,
        ),
    ]
