# Generated by Django 3.0.6 on 2020-05-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0005_auto_20200518_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='userType',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
