# Generated by Django 3.0.6 on 2020-05-18 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0006_auto_20200518_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='userType',
            new_name='userTypeName',
        ),
    ]
