# Generated by Django 3.0.6 on 2020-05-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0007_auto_20200518_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='userTypeId',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
