# Generated by Django 3.0.6 on 2020-05-23 00:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0009_auto_20200522_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menuId',
        ),
        migrations.AlterField(
            model_name='menu',
            name='frequencyOfReocurrence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=7),
        ),
        migrations.AlterField(
            model_name='menu',
            name='isRecurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='itemsOrdered',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
