# Generated by Django 3.0.6 on 2020-05-23 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0011_auto_20200523_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='frequencyOfReocurrence',
        ),
    ]
