# Generated by Django 3.0.6 on 2020-05-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0013_menu_frequencyofreocurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='unit',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
    ]
