# Generated by Django 3.0.6 on 2020-05-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0014_menu_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='frequencyOfReocurrence',
            new_name='frequencyOfReoccurrence',
        ),
    ]
