# Generated by Django 3.0.6 on 2020-05-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0016_auto_20200523_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preOrderDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
