# Generated by Django 3.0.6 on 2020-05-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0017_order_preorderdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amountDue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='amountOutstanding',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='amountPaid',
            field=models.FloatField(),
        ),
    ]
