# Generated by Django 3.0.6 on 2020-05-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0018_auto_20200524_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
