# Generated by Django 3.0.6 on 2020-05-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0019_auto_20200525_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amountPaid',
            field=models.FloatField(default=0),
        ),
    ]
